# Generated by Django 4.2.4 on 2023-08-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('sellerName', models.CharField(max_length=100)),
                ('productDescription', models.TextField()),
                ('pictureLocation', models.TextField()),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
    ]
