# Generated by Django 4.2.4 on 2023-08-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default='300', max_length=10),
        ),
    ]
