# Generated by Django 4.2.4 on 2023-12-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.CharField(max_length=30)),
                ('sellerName', models.CharField(max_length=100, null=True)),
                ('itemDescription', models.TextField(null=True)),
                ('pictureLocation', models.TextField(null=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('price', models.CharField(max_length=10, null=True)),
                ('title', models.CharField(default=None, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active'), ('Sold', 'Sold'), ('Dataset', 'Dataset')], default='Active', max_length=20, null=True)),
                ('url', models.CharField(default=None, max_length=200, null=True)),
                ('platform', models.CharField(default=None, max_length=20, null=True)),
                ('dateTime', models.CharField(default=None, max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
