# Generated by Django 4.2.4 on 2024-01-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_item_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isMatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='matchedId',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
