# Generated by Django 4.2.4 on 2024-01-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_item_ismatched_item_matchedid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.CharField(default=None, max_length=30, null=True)),
                ('matchedId', models.CharField(default=None, max_length=30, null=True)),
            ],
        ),
    ]
