# Generated by Django 4.2.4 on 2024-01-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_matchitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='matchedId',
        ),
        migrations.AddField(
            model_name='item',
            name='matchedCount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
