# Generated by Django 4.2.4 on 2024-02-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_item_matchedid_item_matchedcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imageExist',
            field=models.BooleanField(default=0),
        ),
    ]
