# Generated by Django 4.2.4 on 2024-02-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_groupitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isParent',
            field=models.BooleanField(default=0),
        ),
    ]
