# Generated by Django 4.2.4 on 2024-02-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_item_isparent'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isChild',
            field=models.BooleanField(default=0),
        ),
    ]
