# Generated by Django 4.2.4 on 2024-02-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_item_ischild'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupitems',
            name='groupId',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
