# Generated by Django 4.2.4 on 2024-02-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_groupitems_groupid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupitems',
            old_name='childId',
            new_name='itemId',
        ),
        migrations.RemoveField(
            model_name='groupitems',
            name='parentId',
        ),
    ]
