# Generated by Django 4.2.4 on 2024-02-19 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_rename_childid_groupitems_itemid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='isChild',
            new_name='isGrouped',
        ),
        migrations.RemoveField(
            model_name='item',
            name='isParent',
        ),
    ]
