# Generated by Django 4.2.4 on 2024-02-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_rename_ischild_item_isgrouped_remove_item_isparent'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='groupId',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='groupitems',
            name='groupId',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
