# Generated by Django 4.2.4 on 2024-02-19 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_item_groupid_alter_groupitems_groupid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupItems',
        ),
    ]
