# Generated by Django 4.2.4 on 2024-09-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_delete_groupitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isNewImage',
            field=models.BooleanField(default=0),
        ),
    ]
