# Generated by Django 4.2.4 on 2024-09-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_item_isnewimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isNewGroup',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='isNewMatch',
            field=models.BooleanField(default=0),
        ),
    ]
