# Generated by Django 4.2.4 on 2024-10-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_item_isnewgroup_item_isnewmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
